version: '2'
services:

  web:
    build:
      context: ./web
    image: re351/app:latest
    ports:
    - "8080:8080"
    links:
    - data

  data:
    container_name: data
    build:
      context: ./database
    image: re351/data
