version: '2'
services:

  web:
    build:
      context: ./web
    image: re351/app:latest
    ports:
    - "8080:8080"
    networks:
      app_net:
        ipv4_address: 172.78.238.10

  data:
    container_name: data
    build:
      context: ./database
    image: re351/data
    networks:
      app_net:
        ipv4_address: 172.78.238.11
    
networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.78.238.0/24
        gateway: 172.78.238.1
